[[pages]]
path = "login.py"
name = "Login"
icon = "ğŸ’ "

[[pages]]
path = "views/main.py"
name = "Main"
icon = "ğŸ•Œ"

[[pages]]
path = "views/settings.py"
name = "Settings"
icon = "âš™ï¸"

[[pages]]
path = "views/dashboard.py"
name = "Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "views/messages.py"
name = "Messages"
icon = "ğŸ’¬"

[[pages]]
path = "views/models.py"
name = "Models"
icon = "ğŸ§ "
